server {
    listen 80;
    server_name meraclinic.mrsinghdev.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name meraclinic.mrsinghdev.com;

    ssl_certificate /etc/letsencrypt/live/meraclinic.mrsinghdev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/meraclinic.mrsinghdev.com/privkey.pem;

    root /var/www/meraclinic/frontend/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
